# Exercise 3

https://pandas.pydata.org/pandas-docs/stable/user_guide/reshaping.html

1. Use the preloaded data provided in this notebook and perform a wide-to-long transformation to the data. Follow the instructions stated in the link below: 
    - https://towardsdatascience.com/reshaping-a-pandas-dataframe-long-to-wide-and-vice-versa-517c7f0995ad
2. The end result should be a table with the following column structure:
    - State, Measure, Month, Deaths
3. Submit the practice notebook (ipynb file) with your name in the filename provided below: 
    - \\\\mh.org\\Public\\CO\\CO - DSci Python Community\\Training\\Python_101_Summer2023\\Exercises

In [1]:
import pandas as pd

df = pd.read_csv('//clinisilonhh/ifs/PHI_Access/PHI-CO - DSci Nhan Tran/Python Curriculum Dev/Exercises/exercise4_dataset.csv')
df

,State,Measure,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
0,Alabama,Sum of Influenza Deaths,47.0,39,33.0,10.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN
1,Alaska,Sum of Influenza Deaths,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Arizona,Sum of Influenza Deaths,53.0,54,39.0,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,11.0
3,Arkansas,Sum of Influenza Deaths,22.0,35,29.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,California,Sum of Influenza Deaths,307.0,307,189.0,31.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,Virginia,Sum of Pneumonia Deaths,2935.0,1874,1236.0,1314.0,989.0,649.0,645.0,917.0,1309.0,1263.0,1119.0,1701.0
104,Washington,Sum of Pneumonia Deaths,2026.0,1433,1218.0,1163.0,910.0,610.0,705.0,1020.0,1367.0,1258.0,1190.0,1436.0
105,West Virginia,Sum of Pneumonia Deaths,1248.0,881,607.0,545.0,409.0,266.0,275.0,424.0,701.0,711.0,665.0,880.0
106,Wisconsin,Sum of Pneumonia Deaths,1593.0,925,782.0,693.0,581.0,372.0,385.0,541.0,710.0,1073.0,1557.0,1600.0
107,Wyoming,Sum of Pneumonia Deaths,175.0,138,95.0,75.0,53.0,48.0,67.0,91.0,150.0,189.0,216.0,189.0